class PrivacyPolicyText {
  final String privacyPolicy =
      "Coming soon, Testing pout long tesjodnf  s;dfmm;s knn lfskljf sljjl kdsf"
      "lsdijflisdij d"
      "sdo;fjsoyldjfkj  lisdl ksn lsj lsk lk slkdn lksn lksnd lkd lksnd lkd "
      "lsjdi lksjl;yokishdoilksdj osidj oisj lskdl ksdl slk sdlkn slkk nsl"
      "soiolidj pos;doj dlikns lksdn lksn lkds lksn lksnd lksn dlkknklsn d"
      "spidjlis po;k sjoilid lks dlksn ljosdhlidskndlskknsdlknsdlknsl"
      "oishdoihsdoisdhol osidhodishidoishdoihso psoj spojd posj dpos dpos"
      "iushdoi o isij oiisj oiisdn iois soij oisj sodisd iosoi shoih  osijd"
      "Coming soon, Testing pout long tesjodnf  s;dfmm;s knn lfskljf sljjl kdsf"
      "lsdijflisdij d"
      "sdo;fjsoyldjfkj  lisdl ksn lsj lsk lk slkdn lksn lksnd lkd lksnd lkd "
      "lsjdi lksjl;yokishdoilksdj osidj oisj lskdl ksdl slk sdlkn slkk nsl"
      "soiolidj pos;doj dlikns lksdn lksn lkds lksn lksnd lksn dlkknklsn d"
      "spidjlis po;k sjoilid lks dlksn ljosdhlidskndlskknsdlknsdlknsl"
      "oishdoihsdoisdhol osidhodishidoishdoihso psoj spojd posj dpos dpos"
      "iushdoi o isij oiisj oiisdn iois soij oisj sodisd iosoi shoih  osijd"
      "Coming soon, Testing pout long tesjodnf  s;dfmm;s knn lfskljf sljjl kdsf"
      "lsdijflisdij d"
      "sdo;fjsoyldjfkj  lisdl ksn lsj lsk lk slkdn lksn lksnd lkd lksnd lkd "
      "lsjdi lksjl;yokishdoilksdj osidj oisj lskdl ksdl slk sdlkn slkk nsl"
      "soiolidj pos;doj dlikns lksdn lksn lkds lksn lksnd lksn dlkknklsn d"
      "spidjlis po;k sjoilid lks dlksn ljosdhlidskndlskknsdlknsdlknsl"
      "oishdoihsdoisdhol osidhodishidoishdoihso psoj spojd posj dpos dpos"
      "iushdoi o isij oiisj oiisdn iois soij oisj sodisd iosoi shoih  osijd"
      "Coming soon, Testing pout long tesjodnf  s;dfmm;s knn lfskljf sljjl kdsf"
      "lsdijflisdij d"
      "sdo;fjsoyldjfkj  lisdl ksn lsj lsk lk slkdn lksn lksnd lkd lksnd lkd "
      "lsjdi lksjl;yokishdoilksdj osidj oisj lskdl ksdl slk sdlkn slkk nsl"
      "soiolidj pos;doj dlikns lksdn lksn lkds lksn lksnd lksn dlkknklsn d"
      "spidjlis po;k sjoilid lks dlksn ljosdhlidskndlskknsdlknsdlknsl"
      "oishdoihsdoisdhol osidhodishidoishdoihso psoj spojd posj dpos dpos"
      "iushdoi o isij oiisj oiisdn iois soij oisj sodisd iosoi shoih  osijd"
      "Coming soon, Testing pout long tesjodnf  s;dfmm;s knn lfskljf sljjl kdsf"
      "lsdijflisdij d"
      "sdo;fjsoyldjfkj  lisdl ksn lsj lsk lk slkdn lksn lksnd lkd lksnd lkd "
      "lsjdi lksjl;yokishdoilksdj osidj oisj lskdl ksdl slk sdlkn slkk nsl"
      "soiolidj pos;doj dlikns lksdn lksn lkds lksn lksnd lksn dlkknklsn d"
      "spidjlis po;k sjoilid lks dlksn ljosdhlidskndlskknsdlknsdlknsl"
      "oishdoihsdoisdhol osidhodishidoishdoihso psoj spojd posj dpos dpos"
      "iushdoi o isij oiisj oiisdn iois soij oisj sodisd iosoi shoih  osijd"
      "Coming soon, Testing pout long tesjodnf  s;dfmm;s knn lfskljf sljjl kdsf"
      "lsdijflisdij d"
      "sdo;fjsoyldjfkj  lisdl ksn lsj lsk lk slkdn lksn lksnd lkd lksnd lkd "
      "lsjdi lksjl;yokishdoilksdj osidj oisj lskdl ksdl slk sdlkn slkk nsl"
      "soiolidj pos;doj dlikns lksdn lksn lkds lksn lksnd lksn dlkknklsn d"
      "spidjlis po;k sjoilid lks dlksn ljosdhlidskndlskknsdlknsdlknsl"
      "oishdoihsdoisdhol osidhodishidoishdoihso psoj spojd posj dpos dpos"
      "iushdoi o isij oiisj oiisdn iois soij oisj sodisd iosoi shoih  osijd"
      "iosdjois  oish oish o sdoi iosh oihsd oisd oisdoi ihsiooh soih so";
}
