// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcs_xISd6WywkenyemwnkmNWL4yLIOx2c',
    appId: '1:875402290272:web:1fb2fad94d405a99440f05',
    messagingSenderId: '875402290272',
    projectId: 'beacon-9061b',
    authDomain: 'beacon-9061b.firebaseapp.com',
    databaseURL: 'https://beacon-9061b-default-rtdb.firebaseio.com',
    storageBucket: 'beacon-9061b.appspot.com',
    measurementId: 'G-805JRMFKYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUa5-E552KLCS7dHuXGJVGnLuLRtecAq0',
    appId: '1:875402290272:android:54e80a21eb1dfa63440f05',
    messagingSenderId: '875402290272',
    projectId: 'beacon-9061b',
    databaseURL: 'https://beacon-9061b-default-rtdb.firebaseio.com',
    storageBucket: 'beacon-9061b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZUWE9xY0cAa31ZM2cgLVcVzAtTbK6Hzo',
    appId: '1:875402290272:ios:a79b24ca1093e369440f05',
    messagingSenderId: '875402290272',
    projectId: 'beacon-9061b',
    databaseURL: 'https://beacon-9061b-default-rtdb.firebaseio.com',
    storageBucket: 'beacon-9061b.appspot.com',
    iosClientId: '875402290272-7ptr3c8a3jfgtq52bgpdp9h1jkmr1cf7.apps.googleusercontent.com',
    iosBundleId: 'co.nz.beacon.beacon',
  );
}
